"""
URL configuration for python project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/6.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from .import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('datatypes', views.datatypes , name = "python tutorial"),
    path('python/', views.python , name = "python tutorial"),
    path('listextend', views.listextend , name = "list extend"),
    path('listextendresult', views.listextendresult , name = "list extend result"),
    path('listsorted', views.listsorted, name = "list sorted"),
    path("listsortedresult", views.listsortedresult, name = "list sorted result"),
    path('listappend', views.listappend, name = "list sorted"),
    path("listappendresult", views.listappendresult, name = "list sorted result"),
    path('listinsert', views.listinsert, name = "list sorted"),
    path("listinsertresult", views.listinsertresult, name = "list sorted result"),
    path('listpop', views.listpop, name = "list sorted"),
    path("listpopresult", views.listpopresult, name = "list sorted result"),
    path('list/', views.list , name = "list methods"),
    path('strings/', views.strings , name = "strings methods"),
    path('stringupper/', views.stringupper , name = "string upper"),
    path('stringupperresult/', views.stringupperresult , name = "string upper result"),
    path('stringlower/', views.stringlower , name = "string lower"),
    path('stringlowerresult/', views.stringlowerresult , name = "string lower result"),
    path('stringcapitalize/', views.stringcapitalize , name = "string capitalize"),
    path('stringcapitalizeresult/', views.stringcapitalizeresult , name = "string capitalize result"),
    path('stringtitle/', views.stringtitle , name = "string title"),
    path('stringtitleresult/', views.stringtitleresult , name = "string title result"),
    path('stringstrip/', views.stringstrip , name = "string strip"),
    path('stringstripresult/', views.stringstripresult , name = "string strip result"),
    path('sets/', views.sets , name = "sets methods"),
    path('setsadd/', views.setadd , name = "set add"),
    path('setsaddresult/', views.setaddresult , name = "set add result"),
    path('setsupdate/', views.setupdate , name = "set update"),
    path('setsupdateresult/', views.setupdateresult , name = "set update result"),
    path('setsremove/', views.setremove , name = "set remove"),
    path('setsremoveresult/', views.setremoveresult , name = "set remove result"),
    path('setsdiscard/', views.setdiscard , name = "setdiscard"),
    path('setsdiscardresult/', views.setdiscardresult , name = "set discard result"),
    path('setsunion/', views.setunion , name = "set union"),
    path('setsunionresult/', views.setunionresult , name = "set union result"),
    path('tuples/', views.tuples , name = "tuples methods"),
    path('tuplecount/', views.tuplecount , name = "tuple count"),
    path('tuplecountresult/', views.tuplecountresult , name = "tuple count result"),
    path('tupleindex/', views.tupleindex , name = "tuple index"),
    path('tupleindexresult/', views.tupleindexresult , name = "tuple index result"),
    path('tuplelen/', views.tuplelen , name = "tuple len"),
    path('tuplelenresult/', views.tuplelenresult , name = "tuple len result"),
    path('tuplemax/', views.tuplemax , name = "tuple max"),
    path('tuplemaxresult/', views.tuplemaxresult , name = "tuple max result"),
    path('tuplemin/', views.tuplemin , name = "tuple min"),
    path('tupleminresult/', views.tupleminresult , name = "tuple min result"),
    path('dictionary/', views.dictionary , name = "tuples methods"),
    path('dictget/', views.dictget , name = "dictionary get"),
    path('dictgetresult/', views.dictgetresult , name = "dictionary get result"),
    path('dictkeys/', views.dictkeys , name = "dictionary keys"),
    path('dictkeysresult/', views.dictkeysresult , name = "dictionary keys result"),
    path('dictvalues/', views.dictvalues , name = "dictionary values"),
    path('dictvaluesresult/', views.dictvaluesresult , name = "dictionary values result"),
    path('dictitems/', views.dictitems , name = "dictionary items"),
    path('dictitemsresult/', views.dictitemsresult , name = "dictionary items result"),
    path('dictupdate/', views.dictupdate , name = "dictionary update"),
    path('dictupdateresult/', views.dictupdateresult , name = "dictionary update result"),
    path('operators/', views.operators , name = "dictionary update result"),
    path('operatorexponent/', views.operatorexponent , name = "exponent"),
    path('operatorexponentresult/', views.operatorexponentresult , name = "exponent result"),
    path('operatorunaryplus/', views.operatorunaryplus , name = "unaryplus"),
    path('operatorunaryplusresult/', views.operatorunaryplusresult , name = "unaryplus result"),
    path('operatorunaryminus/', views.operatorunaryminus , name = "unaryminus"),
    path('operatorunaryminusresult/', views.operatorunaryminusresult , name = "unaryminus result"),
    path('operatorbitwisenot/', views.operatorbitwisenot , name = "bitwisenot"),
    path('operatorbitwisenotresult/', views.operatorbitwisenotresult , name = "bitwisenot result"),
    path('operatormultiplication/', views.operatormultiplication , name = "multiplication"),
    path('operatormultiplicationresult/', views.operatormultiplicationresult , name = "multiplication result"),
    path('operatordivision/', views.operatordivision , name = "division"),
    path('operatordivisionresult/', views.operatordivisionresult , name = "division result"),
    path('operatorfloordivision/', views.operatorfloordivision , name = "floor division"),
    path('operatorfloordivisionresult/', views.operatorfloordivisionresult , name = "floor division result"),
    path('operatormodulus/', views.operatormodulus , name = "modulus"),
    path('operatormodulusresult/', views.operatormodulusresult , name = "modulus result"),
    path('operatoraddition/', views.operatoraddition , name = "addition"),
    path('operatoradditionresult/', views.operatoradditionresult , name = "addition result"),
    path('operatorsubtraction/', views.operatorsubtraction , name = "subtraction"),
    path('operatorsubtractionresult/', views.operatorsubtractionresult , name = "subtraction result"),
    path('operatorbsl/', views.operatorbsl , name = "bsl"),
    path('operatorbslresult/', views.operatorbslresult , name = "bsl result"),
    path('operatorbsr/', views.operatorbsr , name = "bsr"),
    path('operatorbsrresult/', views.operatorbsrresult , name = "bsr result"),
    path('operatorbitwiseand/', views.operatorbitwiseand , name = "bitwiseand"),
    path('operatorbitwiseandresult/', views.operatorbitwiseandresult , name = "bitwise and result"),
    path('operatorbitwisexor/', views.operatorbitwisexor , name = "bitwise xor"),
    path('operatorbitwisexorresult/', views.operatorbitwisexorresult , name = "bitwise xor result"),
    path('operatorbitwiseor/', views.operatorbitwiseor , name = "bitwise or"),
    path('operatorbitwiseorresult/', views.operatorbitwiseorresult , name = "bitwise or result"),
    path('operatorisequal/', views.operatorisequal , name ="isequal"),
    path('operatorisequalresult/', views.operatorisequalresult , name = "isequal result"),
    path('operatorisnotequal/', views.operatorisnotequal , name ="isnotequal"),
    path('operatorisnotequalresult/', views.operatorisnotequalresult , name = "isnotequal result"),
    path('operatorgreater/', views.operatorgreater , name ="greater"),
    path('operatorgreaterresult/', views.operatorgreaterresult , name = "greater result"),
    path('operatorsmaller/', views.operatorsmaller , name ="smaller"),
    path('operatorsmallerresult/', views.operatorsmallerresult , name = "smaller result"),
    path('operatorgreaterequal/', views.operatorgreaterequal , name ="greaterequal"),
    path('operatorgreaterequalresult/', views.operatorgreaterequalresult , name = "greater equal result"),
    path('operatorsmallerequal/', views.operatorsmallerequal , name ="smallerequal"),
    path('operatorsmallerequalresult/', views.operatorsmallerequalresult , name = "smaller equal result"),
    path('operatoris/', views.operatoris , name ="is"),
    path('operatorisresult/', views.operatorisresult , name = "is result"),
    path('operatorisnot/', views.operatorisnot , name ="is not"),
    path('operatorisnotresult/', views.operatorisnotresult , name = "is not result"),
    path('operatorin/', views.operatorin , name ="in"),
    path('operatorinresult/', views.operatorinresult , name = "in result"),
    path('operatornotin/', views.operatornotin , name =" not in"),
    path('operatornotinresult/', views.operatornotinresult , name = " not in result"),
    path('operatorlnot/', views.operatorlnot , name =" nlnot"),
    path('operatorlnotresult/', views.operatorlnotresult , name = " logical not result"),
    path('operatorland/', views.operatorland , name =" logical and"),
    path('operatorlandresult/', views.operatorlandresult , name = " logical and result"),
    path('operatorlor/', views.operatorlor , name =" logical or"),
    path('operatorlorresult/', views.operatorlorresult , name = " logical or result"),
    path('operatorassopereq/', views.operatorassopereq , name =" assignment equal"),
    path('operatorassopereqresult/', views.operatorassopereqresult , name = " assignment equal result"),
    path('operatorassopereqpl/', views.operatorassopereqpl , name ="assignment addition"),
    path('operatorassopereqplresult/', views.operatorassopereqplresult , name = " assignment addition result"),
    path('operatorassopereqsu/', views.operatorassopereqsu , name ="assignment subtraction"),
    path('operatorassopereqsuresult/', views.operatorassopereqsuresult , name = " assignment subtraction result"),
    path('operatorassopereqmu/', views.operatorassopereqmu , name ="assignment multiplication"),
    path('operatorassopereqmuresult/', views.operatorassopereqmuresult , name = " assignment multiplication result"),
    path('operatorassopereqdi/', views.operatorassopereqdi , name ="assignment division"),
    path('operatorassopereqdiresult/', views.operatorassopereqdiresult , name = " assignment division result"),
    path('con/', views.con, name ="conditional home"),
    path('conex1/', views.conex1 , name ="example 1"),
    path('conex1result/', views.conex1result , name = " example 1 result"),
    path('conex2/', views.conex2 , name ="example 2"),
    path('conex2result/', views.conex2result , name = " example 2 result"),
    path('conex3/', views.conex3 , name ="example 3"),
    path('conex3result/', views.conex3result , name = " example 3 result"),
    path('conex4/', views.conex4 , name ="example 4"),
    path('conex4result/', views.conex4result , name = " example 4 result"),
    path('conex5/', views.conex5 , name ="example 5"),
    path('conex5result/', views.conex5result , name = " example 5 result"),
    path('loop/', views.loop, name ="conditional home"),
    path('loopex1/', views.loopex1 , name ="example 1"),
    path('loopex1result/', views.loopex1result , name = " example 1 result"),
    path('loopex2/', views.loopex2 , name ="example 2"),
    path('loopex2result/', views.loopex2result , name = " example 2 result"),
    path('loopex3/', views.loopex3 , name ="example 3"),
    path('loopex3result/', views.loopex3result , name = " example 3 result"),
    path('loopex4/', views.loopex4 , name ="example 4"),
    path('loopex4result/', views.loopex4result , name = " example 4 result"),
    path('loopex5/', views.loopex5 , name ="example 5"),
    path('loopex5result/', views.loopex5result , name = " example 5 result"),
    path('func/', views.func, name ="functions home"),
    path('funcex1/', views.funcex1 , name ="example 1"),
    path('funcex1result/', views.funcex1result , name = " example 1 result"),
    path('funcex2/', views.funcex2 , name ="example 2"),
    path('funcex2result/', views.funcex2result , name = " example 2 result"),
    path('funcex3/', views.funcex3 , name ="example 3"),
    path('funcex3result/', views.funcex3result , name = " example 3 result"),
    path('funcex4/', views.funcex4 , name ="example 4"),
    path('funcex4result/', views.funcex4result , name = " example 4 result"),
    path('funcex5/', views.funcex5 , name ="example 5"),
    path('funcex5result/', views.funcex5result , name = " example 5 result"),
    path('rec/', views.rec, name ="recursion home"),
    path('recex1/', views.recex1 , name ="example 1"),
    path('recex1result/', views.recex1result , name = " example 1 result"),
    path('recex2/', views.recex2 , name ="example 2"),
    path('recex2result/', views.recex2result , name = " example 2 result"),
    path('recex3/', views.recex3, name ="example 3"),
    path('recex3result/', views.recex3result , name = " example 3 result"),
    path('recex4/', views.recex4 , name ="example 4"),
    path('recex4result/', views.recex4result , name = " example 4 result"),
    path('recex5/', views.recex5 , name ="example 5"),
    path('recex5result/', views.recex5result , name = " example 5 result"),
    path('cred/', views.cred, name ="credits")
]

